### ISSUE TITLE
Join forces with OpenAPITools/openapi-diff project

### ISSUE THREAD

**Issue by joschi** [wheatstalk/openapi-diff-maven-plugin#2]
Thanks for building this useful Maven plugin!

Would you be interested to merge it with the "upstream" [OpenAPITools/openapi-diff](https://github.com/OpenAPITools/openapi-diff) project and keep maintaining the Maven plugin there?

I think people would generally find it useful (https://github.com/OpenAPITools/openapi-diff/issues/152).

**Comment by misterjoshua** [comment]
That sounds like a good idea. How shall we proceed? Would you like a PR?

**Comment by joschi** [comment]
@misterjoshua Awesome, thanks for the quick response! 😄 

Let me first ask the admins of the OpenAPITools organization add you as a collaborator on the repository, and then we could move the code there.

**Comment by misterjoshua** [comment]
> 
> 
> @misterjoshua Awesome, thanks for the quick response! 😄
> 
> Let me first ask the admins of the OpenAPITools organization add you as a collaborator on the repository, and then we could move the code there.

Sounds like a plan. In the meantime, I've [created a PR](https://github.com/OpenAPITools/openapi-diff/pull/278) so that we can collaborate.

**Comment by joschi** [comment]
Thank you so much for your positive and quick response. You've been added as a collaborator to the OpenAPITools/openapi-diff repository and I've left my comment (and approval) on your pull request.

I consider this particular issue being complete and will close it. 😄
